AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "test/**/*"

Metrics/ParameterLists:
  Max: 12

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "test/**/*"

Layout/LineLength:
  Exclude:
    - "test/**/*"

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/ClassLength:
  Max: 150
  Exclude:
    - "test/**/*"

Metrics/ModuleLength:
  Max: 250
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/DuplicatedAssignment:
  Enabled: false
